### ISSUE TITLE
using quarterly data to forecast quarterly variable

### ISSUE THREAD

**Issue by raiZel1996** [nmecsys/nowcasting#10]
sorry in advance, But I honestly don't know where can I ask for help regarding this question.
I just want to ask for advice regarding using explanatory variables that are of frequency=4 to forecast gdp with frequency of 4, is that possible using 2s and 2s_agg method
thank you in advance any help will be much appreciated

**Comment by carloshilal** [comment]
Yo raiZel1996, I am not sure regarding exactly what kind of advice it is that you are seeking; however, within my current knowledge I can tell you that, yes, you could forecast (using any of the nowcasting methods) quarterly gdp using only quarterly variables as long as these quarterly variables are published earlier. You would also have less nowcast horizons, and I think that accuracy would be weak.  
I am not sure however, that this methodology would be smart to use in that case though, since the models was specifically built for the use of lower frequency variables to forecast higher frequency ones. 
Hope that my answer helps, wish you the best.

**Comment by raiZel1996** [comment]
Hi @carloshilal , I really appreciate your response, it means a lot to me. thank you for taking the time to answer me.
I ma doing this as a part of my graduation paper where I use multiple models to forecast using GDP using quarterly data ( it is the only one available) and i am really stuck in his model. 
here is a short version of the code I am using 
x <- Bpanel(base = base, trans =trans)
y1<-ts(y1,start=c(2000,1),end=c(2020,4), frequency=4)
x1<-x1[,-47] # removing GDP from x
data <- cbind(y1,x1)
frequency <- c(4,rep(4,ncol(x1)))
now <- nowcast(formula = y1~., data = data, r =2, q =2, p = 2, method = "2s",frequency = frequency) ( I still need to change the variables I am using and number of factors but I just want to find the right way before starting to do that.)
the problem is when I pass it this way is nowcast the range of my observation shrinks instead of working from 2000Q1 to 2020Q4 it just goes up to 2006Q1. so I was wondering if there was a specific way so I can use quarterly data to forecast quarterly GDP. like what do I need to change in order to use quarterly data without losing observations.
thank you so much and sorry if I am not clear
![focast y](https://user-images.githubusercontent.com/87086162/125160962-82fe6500-e177-11eb-968e-cd68053beaec.png)
